on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: cboot
      - name: Prep Build Environment
        uses: actions/checkout@v2
        with:
          repository: waggle-sensor/nvidia_toolchain
          ref: refs/heads/master
          path: toolchain
          lfs: true
      - name: Build project
        id: build_project
        run: |
          pushd ${{ github.workspace }}/toolchain
          tar xf $(ls *.xz)
          popd
          pushd ${{ github.workspace }}/cboot
          ./build.sh -t ${{ github.workspace }}/toolchain/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu
          gzip $(ls *.bin)
          popd
          echo "##[set-output name=cboot_gz_path;]$(ls cboot/*.gz)"
          echo "##[set-output name=cboot_gz_name;]$(basename $(ls cboot/*.gz))"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset (Registration)
        id: upload-release-asset-registration
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./${{ steps.build_project.outputs.cboot_gz_path }}
          asset_name: ${{ steps.build_project.outputs.cboot_gz_name }}
          asset_content_type: application/gzip
